plan:
    package: ./2021/dagger/ci
name: ci
inputs:
    app:
        dir:
            path: .
            exclude:
                - .circleci
                - .dagger
                - .git
                - .github
                - "2021"
                - "2022"
                - _build/dev
                - _build/test
                - assets/node_modules
                - cue.mod
                - dev_docker
                - docker
                - import
                - nginx
                - priv/db
                - priv/uploads
                - script
                - tmp
                - .all-contributorsrc
                - .autocomplete
                - .credo.exs
                - .dockerignore
                - .formatter.exs
                - .envrc
                - .env
                - .gitattributes
                - .gitignore
                - .kube
                - coveralls.json
                - start_dev_stack.sh
                - erl_crash.dump
                - deps
    docker_host:
        text: tcp://100.113.182.91:2375
    dockerfile:
        text: |
            FROM thechangelog/legacy_assets AS legacy_assets
            FROM thechangelog/runtime:2021-05-29T10.17.12Z

            RUN mkdir /app
            COPY /app /app
            WORKDIR /app
            RUN ls -lah
            RUN exit 1

            COPY --from=legacy_assets /var/www/wp-content /app/priv/wp-content

            ENV MIX_ENV=prod
            ENV TERM=xterm

            # Used by PromEx for annotations
            ARG APP_VERSION
            ARG GIT_SHA
            ARG GIT_AUTHOR
            ENV APP_VERSION=${APP_VERSION}
            ENV GIT_SHA=${GIT_SHA}
            ENV GIT_AUTHOR=${GIT_AUTHOR}

            EXPOSE 4000

            CMD make on-app-start; mix do ecto.create, ecto.migrate, phx.server
    prod_dockerfile:
        text: |
            FROM thechangelog/legacy_assets AS legacy_assets
            FROM thechangelog/runtime:2021-05-29T10.17.12Z

            RUN mkdir /app
            COPY /app /app
            WORKDIR /app
            RUN ls -lah
            RUN exit 1

            COPY --from=legacy_assets /var/www/wp-content /app/priv/wp-content

            ENV MIX_ENV=prod
            ENV TERM=xterm

            # Used by PromEx for annotations
            ARG APP_VERSION
            ARG GIT_SHA
            ARG GIT_AUTHOR
            ENV APP_VERSION=${APP_VERSION}
            ENV GIT_SHA=${GIT_SHA}
            ENV GIT_AUTHOR=${GIT_AUTHOR}

            EXPOSE 4000

            CMD make on-app-start; mix do ecto.create, ecto.migrate, phx.server
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ag8qa42h7up3p3xngup00ps36uvyek59ppc9z4wxq7rwk4pjcaus4aya7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MmhnMHFZZS9Ea3lUTm5D
            ck1mUXhIYUZVOHpkRXlBaEI2VnpaK0J5VUZJCmdpb3RJTnprT2pCbVJIYVR2eVor
            ajFrWlczWmxiVHd0ZU8rUWRsRjU2OWcKLS0tIEg2WG5IWUc1ZzZ5SXBOVHdMdDlM
            cmdMbkpUL1djUlAxZzJZY3BKS2FHSHcKPnWXKGjp3SrIninwwtth5YNFNdFZaE+H
            1EilpFF7Tn/RQNLcv257uofciczvXiOPwn+f7QJwF7zCaifNENbuhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-19T17:21:34Z"
    mac: ENC[AES256_GCM,data:QbJQKo9pD0zIQXjWmAr5k/ry/HvCT3E6c5IGPc9gr+ya+KnH+VpmepzVfZH8NfEguu47hWt9KkN/dUxDhujJl/mQIbKrS7YerSzCINLMyCU0n6HSzhn1m2bfyxW8l4hcy6H+/rYSOr3PvkzhrXBeuQ1sPesZ1GoAUjTD3hXbnAI=,iv:0bbrN8gLdxh3/RUkV5pfiayVPNd93CLIjSUf4xuyO1k=,tag:pSQBm+nz9aZX2YBqImaecA==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
