plan:
    package: ./2021/dagger/ci
name: ci
inputs:
    app:
        dir:
            path: .
            exclude:
                - .circleci
                - .dagger
                - .git
                - .github
                - "2021"
                - "2022"
                - _build/dev
                - _build/test
                - assets/node_modules
                - cue.mod
                - dev_docker
                - docker
                - import
                - nginx
                - priv/db
                - priv/uploads
                - script
                - tmp
                - .all-contributorsrc
                - .autocomplete
                - .credo.exs
                - .dockerignore
                - .formatter.exs
                - .envrc
                - .env
                - .gitattributes
                - .gitignore
                - .kube
                - coveralls.json
                - start_dev_stack.sh
                - erl_crash.dump
                - deps
    docker_host:
        text: tcp://100.113.182.91:2375
    dockerhub_password:
        secret: ENC[AES256_GCM,data:mux+4PIvbF1yivwRRJFQSQeocA==,iv:Na9nUxzm4X+RBUzdAjZeGrZWBuZkC9EmGM+5z3EdC9Q=,tag:rH5yCbj2SrA3t3PXj5T82g==,type:str]
    dockerhub_username:
        text: gerhard
    prod_dockerfile:
        text: |
            FROM thechangelog/legacy_assets AS legacy_assets
            FROM thechangelog/runtime:2021-05-29T10.17.12Z

            RUN mkdir /app
            COPY /app /app
            WORKDIR /app
            RUN ls -lah
            RUN exit 1

            COPY --from=legacy_assets /var/www/wp-content /app/priv/wp-content

            ENV MIX_ENV=prod
            ENV TERM=xterm

            # Used by PromEx for annotations
            ARG APP_VERSION
            ARG GIT_SHA
            ARG GIT_AUTHOR
            ENV APP_VERSION=${APP_VERSION}
            ENV GIT_SHA=${GIT_SHA}
            ENV GIT_AUTHOR=${GIT_AUTHOR}

            EXPOSE 4000

            CMD make on-app-start; mix do ecto.create, ecto.migrate, phx.server
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ag8qa42h7up3p3xngup00ps36uvyek59ppc9z4wxq7rwk4pjcaus4aya7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOEVoWmhTc2M3eTMyRmsw
            aHErM3ljcFl0NDhDM1B0dllVTE50NlZRYXdvCkhiYXExbXRDaC82UnJQd3dVaysy
            YWxnS0Y2cFlkdlM5ZWMwb0EvKzhzT0UKLS0tIHZvMWFxdDFGbTBsY3c3dkhuRXIz
            SnF2bUoyV2kzMHVFMW1QSXg1MkxQNXcKK8gEBqG3EE4cquSUoQpC9OcFdUl/aJn3
            a3OhLCZLkB9/8CEd5IQ5QtUvIBK3fQe+3/zNkTNRLvay3OmWwKB8cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-22T08:57:26Z"
    mac: ENC[AES256_GCM,data:7jEnYiokYkrbLsJcRhxfV9oMVZbkZKB+9Yc4AlvJk184dVGvCjoAE48pLEWFO139o/IJTytKhjVrRwRj9zqMUQA/IHV9L2PXI1Dr59NiBr/TJdxM/8xdGGTmVCq/4mpZycEdZTnEmsnSJIv4iCz6HZA5hrTu4aOKd/9QZsf68fg=,iv:WSbQ1U3ounfVSYqVW+oShJkAThltho5NODpkik7YAHo=,tag:xUHZj4sHq7C0Bqh8KPoCIQ==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
