plan:
    package: ./2021/dagger/ci
name: ci
inputs:
    app:
        dir:
            path: .
            exclude:
                - .circleci
                - .dagger
                - .git
                - .github
                - "2021"
                - "2022"
                - _build/dev
                - _build/test
                - assets/node_modules
                - cue.mod
                - dev_docker
                - docker
                - import
                - nginx
                - priv/db
                - priv/uploads
                - script
                - tmp
                - .all-contributorsrc
                - .autocomplete
                - .credo.exs
                - .dockerignore
                - .formatter.exs
                - .envrc
                - .env
                - .gitattributes
                - .gitignore
                - .kube
                - coveralls.json
                - start_dev_stack.sh
                - erl_crash.dump
                - deps
    docker_socket:
        socket:
            unix: /var/run/docker.sock
    dockerhub_password:
        secret: ENC[AES256_GCM,data:fldDnjY0YR8MJmua,iv:XWm62ByPmXgLuXfqSp0gVdKRfnJUv4ssGnIeVJkq43s=,tag:MYnqajLlBCr/2+UmbePTxA==,type:str]
    dockerhub_username:
        text: grouville
    prod_dockerfile:
        text: |
            FROM thechangelog/legacy_assets AS legacy_assets
            FROM thechangelog/runtime:2021-05-29T10.17.12Z

            RUN mkdir /app
            COPY /app /app
            WORKDIR /app
            RUN ls -lah

            COPY --from=legacy_assets /var/www/wp-content /app/priv/wp-content

            ENV MIX_ENV=prod
            ENV TERM=xterm

            # Used by PromEx for annotations
            ARG APP_VERSION
            ARG GIT_SHA
            ARG GIT_AUTHOR
            ENV APP_VERSION=${APP_VERSION}
            ENV GIT_SHA=${GIT_SHA}
            ENV GIT_AUTHOR=${GIT_AUTHOR}

            ARG BUILD_URL
            ENV BUILD_URL=${BUILD_URL}
            # Used by various tooling to report the identity & origin of this build
            RUN echo "$GIT_SHA" > priv/static/version.txt \
                ; echo "$GIT_AUTHOR" > COMMIT_USER \
                ; echo "$BUILD_URL" > priv/static/build.txt

            EXPOSE 4000

            CMD make on-app-start; mix do ecto.create, ecto.migrate, phx.server
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSXdOaVpFMy9aS05sRjhL
            eHF4WXRYdmp2cUVpSDhpT1c4ejJuS3BPWnhZClJKTHFaY09zMzBOV1BBUXFzUWNK
            bElwanN4Wjg0RmtIRUZZZUllVlBCMkEKLS0tIHQ3Q0RERm9GZkJGanM2cTd5Uldw
            eG81RzRINmxJSTYxdWQxTjM5ZjJNY0UKjwy2eSMewQ54pgJb3bnoo8mp4qZ9fwcW
            jCdc0hHUHfeXcM+nn/jafZdGjVT0qhV3p8bxQrxvZRj8N+shii5hgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-25T08:11:58Z"
    mac: ENC[AES256_GCM,data:pO5Bw5YsKmOcIGLpYRX8aiqodotiRZcXKqHhYsfLnIFjvAQmJC61MH12SpOAkCHN7Iaoi0NxFZKKFNIHf/7SJhRnZCXg0NmsoWJ1ZaZCYGbrtyoXFQolM5UXljghOKN0fSqKVrsHH4uCn0wDCmDz7cjILZFLOifceEJW0FjQjTs=,iv:FbB+4wAUiNYOhdIGQvNYDP4YJd06F7BuBJhD7lv/LNI=,tag:u+9342zLUrdgJ0ZkoYiSLg==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
